name: Mac CI and RATS

on:
  workflow_dispatch:
    inputs:
      force-rebuild-deps:
        description: 'Force rebuild dependencies'
        default: false
        required: false
        type: boolean
  push:
    branches:
      - main

jobs:
  CI_and_RATS:
    env:
      CHATROOM: ${{ secrets.TRIGGER_CI_CHATROOM }}
      workspace: ${{ github.workspace }}
    runs-on: [self-hosted, macOS]
    steps:
      - name: Cleanup previous run
        if: always()
        shell: bash
        run: |
          cd ${workspace}
          rm -rf build-deps build source installs/openmoonray
      - name: Clone openmoonray
        uses: actions/checkout@v3
        with:
          path: source/openmoonray
          repository: dwanim/openmoonray
          token: ${{ secrets.BART_TOKEN }}
          submodules: recursive
          lfs: true
      - name: Check for new dependencies
        env:
            FORCE_REBUILD: ${{ inputs.force-rebuild-deps }}
        shell: bash
        run: |
          if [ ! cmp -s ${workspace}/CMakeLists.txt ${workspace}/source/openmoonray/building/macOS/CMakeLists.txt ] || [ "${FORCE_REBUILD}" == "true" ]
          then
            rm -rf ${workspace}/CMakeLists.txt ${workspace}/installs
          fi
      - name: Build dependencies
        shell: bash
        run: |
          umask 0
          if [ ! -d ${workspace}/installs ]
          then
            mkdir -p ${workspace}/{installs/{bin,lib,include},build-deps}
            cd ${workspace}/build-deps
            cmake ${workspace}/source/openmoonray/building/macOS
            cmake --build .
            cp -f ${workspace}/source/openmoonray/building/macOS/CMakeLists.txt ${workspace}/CMakeLists.txt
          fi
      - name: Build
        shell: bash
        working-directory: ./source/openmoonray
        run: |
          umask 0
          mkdir -p ${workspace}/{installs/openmoonray,build}
          cmake --preset dwa-macos-release
          cmake --build --preset dwa-macos-release
          chmod -R go+w ${workspace}/build
      - name: Run unit tests
        shell: bash
        working-directory: ./build
        run: |
          umask 0
          ctest -C Release -L unit -j $(sysctl -n hw.physicalcpu)
      - name: Run RATS tests
        env:
          RATS_CANONICAL_DIR: /Applications/MoonRay/rats_canonicals
        shell: bash
        working-directory: ./build
        run: |
          umask 0
          source ${workspace}/installs/openmoonray/Release/scripts/setup.sh
          ctest -C Release -L rats -L 'render|diff' --output-on-failure  -j $(sysctl -n hw.physicalcpu)

